version: '3.1'
services:
  app:
    container_name: dockerrestpg
    image: dockerrestpg
    build: ./
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=JAmbg172
      - POSTGRES_USER=postgres
      - POSTGRES_URL=jdbc:postgresql://dbpostgresql:5432/usuarios
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    volumes:
      - posgresdocker-data:/var/lib/postgres 
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=JAmbg172*
      - POSTGRES_USER=postgres
      - POSTGRES_DB=usuarios
volumes: 
  posgresdocker-data:
  
      
      
     